### ISSUE TITLE
最新的 sobooks 可以爬取吗

### ISSUE THREAD

**Issue by Skyball** [yeshaobin/Node_Crawler#1]
没有尝试 先问一下 谢谢

**Comment by yeshaobin** [comment]
可以的，网站做了少许改变，你翻墙再爬就行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yeshaobin/Node_Crawler"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月10日(星期四) 下午3:56
收件人:&nbsp;"yeshaobin/Node_Crawler"<Node_Crawler@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[yeshaobin/Node_Crawler] 最新的 sobooks 可以爬取吗 (#1)





 
没有尝试 先问一下 谢谢

**Comment by Skyball** [comment]
试了一下 下载的链接没有提取到

**Comment by yeshaobin** [comment]
网站有一点改变，你观察一下就知道了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yeshaobin/Node_Crawler"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月10日(星期四) 下午4:19
收件人:&nbsp;"yeshaobin/Node_Crawler"<Node_Crawler@noreply.github.com&gt;;
抄送:&nbsp;"yeshaobin"<983281057@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [yeshaobin/Node_Crawler] 最新的 sobooks 可以爬取吗 (#1)





 
试了一下 下载的链接没有提取到

**Comment by Skyball** [comment]
嗯嗯 提取到链接后 有工具可以批量直接下载资源的吗

**Comment by yeshaobin** [comment]
有的 写代码可以下载的



---原始邮件---
发件人: "Skyball"<notifications@github.com&gt;
发送时间: 2020年12月10日(周四) 下午4:24
收件人: "yeshaobin/Node_Crawler"<Node_Crawler@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"yeshaobin"<983281057@qq.com&gt;;
主题: Re: [yeshaobin/Node_Crawler] 最新的 sobooks 可以爬取吗 (#1)




 
嗯嗯 提取到链接后 有工具可以批量直接下载资源的吗

**Comment by Skyball** [comment]
好的 谢谢

**Comment by yeshaobin** [comment]
大佬你要不要我之前已经下载完的sql文件数据库 大概9000本电子书




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yeshaobin/Node_Crawler"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月10日(星期四) 下午5:15
收件人:&nbsp;"yeshaobin/Node_Crawler"<Node_Crawler@noreply.github.com&gt;;
抄送:&nbsp;"yeshaobin"<983281057@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [yeshaobin/Node_Crawler] 最新的 sobooks 可以爬取吗 (#1)





 
Closed #1.

**Comment by Skyball** [comment]
不用啦 我也下载下来了 谢谢~

**Comment by yeshaobin** [comment]
大佬我是在校学生，有点问题想问问您，请问能加一下微信吗？ 我微信是13413144129

---原始邮件---
发件人: "Skyball"<notifications@github.com&gt;
发送时间: 2020年12月15日(周二) 下午5:18
收件人: "yeshaobin/Node_Crawler"<Node_Crawler@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"yeshaobin"<983281057@qq.com&gt;;
主题: Re: [yeshaobin/Node_Crawler] 最新的 sobooks 可以爬取吗 (#1)




 
不用啦 我也下载下来了 谢谢~
